In [1]:
import numpy as np

In [2]:
A = np.array([[1,0,2],[0,2,1],[2,0,3]])

In [3]:
LHS = np.linalg.matrix_power(A,3) - np.linalg.matrix_power(A,2)*6 + A*7 + np.eye(3)*2

In [4]:
print(LHS)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
